
spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb+srv://pawan6186:AKNQzcWBpaYJ3aaW@cluster0.vx89hdm.mongodb.net/?retryWrites=true&w=majority}
  application:
    name: profile-management
springdoc:
  pathsToMatch: /api/**
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
